# [Speedtest-tracker](https://github.com/alexjustesen/speedtest-tracker) is a
# self-hosted internet performance tracking application that runs speedtest
# checks against Ookla's Speedtest service.

---
version: "2.1"
services:
  speedtest-tracker:
    image: ghcr.io/linuxserver/speedtest-tracker
    container_name: speedtest-tracker
    environment:
      # for UserID
      - PUID=${PUID:-1024}
      # for GroupID
      - PGID=${PGID:-100}
      # specify a timezone to use, see this [list](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List).
      - TZ=${TZ:-Europe/Amsterdam}
      # Set the database type to use. `sqlite`, `pgsql`, or `mysql`
      - DB_CONNECTION=sqlite
      # App key used for encrypting stored data. Generate with `docker exec speedtest-tracker php /app/www/artisan key:generate --show`
      - APP_KEY= # optional
      # Database hostname (postgres/mysql).
      - DB_HOST= # optional
      # Database port (postgres/mysql).
      - DB_PORT= # optional
      # Database name (postgres/mysql).
      - DB_DATABASE= # optional
      # Database username (postgres/mysql).
      - DB_USERNAME= # optional
      # Database password (postgres/mysql).
      - DB_PASSWORD= # optional
    volumes:
      # Contains speedtest-tracker config and database, if using sqlite.
      - ${BASEDIR:-/volume1/docker}/speedtest-tracker/config:/config
    ports:
      # Web UI
      - 80:80
    restart: unless-stopped
